### ISSUE TITLE
Would be super awesome to use this to add Gobot support for Hues.

### ISSUE THREAD

**Issue by juliancheal** [evanphx/lights#1]
Hey Evan,

This looks great! We have support in Cylon.js for [Philips Hue](http://cylonjs.com/documentation/platforms/hue), would be great to add it into [Gobot](http://gobot.io).
I don't have a Hue yet so not sure if I'd be able to test this in Gobot, but @deadprogram maybe able to help.

**Comment by evanphx** [comment]
Sure! Just let me know what you need to add it!
